name: Update Coding Test

on:
  push:
    branches:
      - main

jobs:
  update-coding-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name 'NuyHesHUB'
          git config user.email 'shjoo@intube.kr'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser gitpython

      - name: Get changed files
        id: changed-files
        run: |
          commit_count=$(git rev-list --count HEAD)
          if [ $commit_count -gt 0 ]; then
            if [ $commit_count -gt 1 ]; then
              git diff --name-only HEAD~1 HEAD > changed_files.txt
            else
              echo "Only one commit found" > changed_files.txt
            fi
          else
            echo "No commits found" > changed_files.txt
          fi
          cat changed_files.txt

      - name: Run Python script
        run: |
          python scripts/update_coding_test.py
        env: 
          CHANGED_FILES: ${{ steps.changed-files.outputs.files }}

      - name: Pull and Push changes
        run: |
          git pull origin main
          git push https://${{ secrets.GH_PAT_VELOG }}@github.com/NuyHesHUB/coding-test-javascript.git