name: Update Coding Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-coding-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install gitpython

      # Set the locale for the environment globally
      - name: Set locale to UTF-8
        run: sudo update-locale LANG=en_US.UTF-8

      - name: Run Python script
        env:
          LANG: ko_KR.UTF-8
          LANGUAGE: ko_KR:ko
          LC_ALL: ko_KR.UTF-8
        run: python scripts/update_coding_test.py

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_COTE }}
        run: |
          git config user.name 'NuyHesHUB'
          git config user.email 'shjoo@intube.kr'

          # Fetch the latest changes from the repository
          git fetch origin

          # Pull the latest changes and handle rebase if necessary
          git pull origin main --rebase

          # Add all changed files, commit and push
          git add .
          git commit -m "Update coding test" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/NuyHesHUB/coding-test-javascript.git || echo "No changes to push"
