name: Update Coding Test

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  update-coding-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen ko_KR.UTF-8
          sudo update-locale LANG=ko_KR.UTF-8
          pip install gitpython

      - name: Run Python script
        env:
          LANG: ko_KR.UTF-8
          LANGUAGE: ko_KR:ko
          LC_ALL: ko_KR.UTF-8
        run: python scripts/update_coding_test.py

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_COTE }}
        run: |
          git config user.name 'NuyHesHUB'
          git config user.email 'shjoo@intube.kr'
          git stash
          git pull origin main --rebase
          git stash pop
          git add .
          git commit -m "Update coding test" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/NuyHesHUB/coding-test-javascript.git || echo "No changes to push"
