name: Update Coding Test

on:
  push:
    branches:
      - main

  workflow_dispatch: # 수동 실행을 위한 이벤트 추가

jobs:
  update-coding-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name 'NuyHesHUB'
          git config user.email 'shjoo@intube.kr'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser gitpython

      - name: Run Python script
        run: python scripts/update_coding_test.py

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
          
      - name: Pull and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_COTE }}
        run: |
          git pull origin main
          git add .
          git commit -m "Update coding test"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/NuyHesHUB/coding-test-javascript.git